[general]
port = 3001
dyn_data_dir = "apimock-data"
# always = "{ greetings: \"Hello, world.\" }"

[url]
data_dir = "tests"
path_prefix = "api/v1"
[url.paths]
"home" = "home.json"
"some/path" = "api.json5"
# custom header
"some/path/w/header" = { text = "api.json5", headers = ["auth_1", "auth_2"] }
# errors / redirects * code must be unsigned integer
"error/401" = { code = 401 }
"error/api-403" = { code = 403 }
"redirect/302" = { code = 302, headers = ["auth_2"] }
[url.raw_paths]
"/" = { src = "home.json", code = 202 }
[url.headers]
auth_1 = { key = "Authorization", value = "xxx" }
auth_2 = { key = "Location", value = "xxxxxx" }
