[general]
port = 3001
dyn_data_dir = "apimock-data"
# always = "{ greetings: \"Hello, world.\" }"

[url]
data_dir = "tests"
path_prefix = "api/v1"

[url.headers]
auth_1 = { key = "Authorization", value = "xxx" }
redirect_1 = { key = "Location", value = "xxxxxx" }

[url.paths]
"home" = "home.json"
# "some/path" = "api.json5"
# custom header
"some/path/w/header" = { src = "home.json", headers = ["auth_1"] }
# errors / redirects * code must be unsigned integer
"error/401" = { code = 401 }
"error/api-403" = { code = 403 }
"redirect/302" = { code = 302, headers = ["redirect_1"] }

[url.raw_paths]
"/" = { text = "{ Hello: world }", code = 202, headers = ["auth_1", "redirect_1"] }
