[package]
name = "json-responder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { version = "0.3", default-features = false, features = ["compression"] }
toml = "^0.8"
serde = "1"
json5 = "^0.4"
console = "^0.15"
