[package]
name = "json-responder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["server", "http1", "http2", "tcp"] }
toml = "^0.8"
serde = "1"
serde_json = "1"
json5 = "^0.4"
console = "^0.15"
