[package]
name = "json-responder"
version = "1.0.1"
edition = "2021"
description = "Server generating JSON responses written in Rust"

# shrink executable
[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["server", "http1", "http2", "tcp"] }
toml = "^0.8"
serde = "1"
serde_json = "1"
json5 = "^0.4"
console = "^0.15"
