[package]
name = "apimock"
version = "2.7.1"

edition = "2021"
authors = ["nabbisen <nabbisen@scqr.net>"]
license = "Apache-2.0"

description = "API mock Server generating HTTP/JSON responses written in Rust"
repository = "https://github.com/nabbisen/apimock-rs"
readme = "README.md"
categories = ["web-programming", "development-tools", "command-line-utilities"]
keywords = ["https", "api", "mock", "testing"]
rust-version = "1.78.0"

[profile.release]     # shrink executable size
opt-level = "z"
lto = true
panic = "abort"
strip = true
codegen-units = 1

[features]
spawn = [] # offers another entry point for subprocess

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["server", "http1", "http2"] }
hyper-util = { version = "^0.1", features = ["server", "http1", "http2", "tokio"] }
http-body-util = "^0.1"
toml = "^0.8"
serde = "1"
serde_json = "1"
json5 = "^0.4"
console = "^0.15"
log = "0.4.25"

[dev-dependencies]
hyper = { version = "1", features = ["client"] }
