[package]
name = "apimock"
version = "2.4.2"
edition = "2021"
authors = ["nabbisen <nabbisen@scqr.net>"]
license = "ISC"
description = "API mock Server generating HTTP/JSON responses written in Rust"
repository = "https://github.com/nabbisen/apimock-rs"
readme = "README.md"
categories = ["web-programming", "development-tools", "command-line-utilities"]
keywords = ["https", "api", "mock", "testing"]
rust-version = "1.74.0"

# shrink executable
[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["server", "http1", "http2", "tcp"] }
toml = "^0.8"
serde = "1"
serde_json = "1"
json5 = "^0.4"
console = "^0.15"

[dev-dependencies]
hyper = { version = "0.14", features = ["client"] }
