[general]
port = 3001
data_dir = "tests"
# always = "{ greetings: \"Hello, world.\" }"

[url]
path_prefix = "api/v1"
[url.paths]
home = "home.json"
# "some/path" = "api.json5"
[url.errors]
401 = ["api-401"]
403 = ["some/path/to/fail"]
404 = []
