# delay_response_milliseconds is set per-rule, on `respond`.

[[rules]]
when.request.url_path = "/fast"
respond.text = "instant response"

[[rules]]
when.request.url_path = "/slow"
respond = { text = "eventually...", delay_response_milliseconds = 800 }

[[rules]]
when.request.url_path = "/very-slow"
respond = { text = "much later...", delay_response_milliseconds = 2000 }
