[book]
title = "apimock-rs (API Mock) Docs"
authors = ["nabbisen"]
description = "apimock-rs (API Mock) Docs: A developer-friendly, featherlight and functional HTTP(S) mock server built in Rust."

language = "en"

src = "src"

[build]
build-dir = "book"

# mermaid extension
[preprocessor.mermaid]
command = "mdbook-mermaid"
[output.html]
git-repository-url = "https://github.com/apimokka/apimock-rs"
edit-url-template = "https://github.com/apimokka/apimock-rs/edit/main/docs/{path}"

additional-js = ["src/assets/mdbook/mermaid.min.js", "src/assets/mdbook/mermaid-init.js"]

[output.html.search]
enable        = true
limit-results = 20
